/**
 * Validate BPAY Payment API
 * When a payment is submitted to a Financial Institution, the Financial Institution is required to validate the payment details when accepting it. This API validates the payment details for the Settlement Date specified in a request. This API provides functionality to perform BPAY payment validation before payment is submitted.   * This validation result is correct as at the time of calling the API Service.   * The Validate BPAY Payment API does not result in a payment being submitted to BPAY for processing. The Payment Instruction must be submitted to your financial institution (or BPAY if you are a Scheme Member) before cut-off on the same Business Banking Day as the Settlement date specified in a request.   * A maximum of 200 payment records may be included in a request. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: operations@bpay.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Error code and description for an invalid payment detail request.
*/
export class ValidationSummary {
    /**
    * Returns a response code that indicates the result of validation. A value of '0' indicates that the transaction passed validation. Any non-zero value indicates that the payment failed validation.   * 107   * 109   * 113   * 115   * 116   * 122   * 128   * 130   * 131   * 132   * 133   * 140 
    */
    'validationResponseCode'?: string;
    /**
    * If the transaction did not pass validation, then a human readable description of the validation error will be provided. * 107 - The BPAY Biller code is not valid. Please check your entry and try again. * 109 - The Payment Method is not accepted by the Biller. Please enter a different Payment Method. * 113 - The BPAY Customer Reference Number you have entered is not valid. Please check your entry and try again. * 115 - The amount entered is not numeric. Please remove any special characters such as ',' or '$' and try again. * 116 - The amount entered is less than the minimum amount accepted by the Biller.  Please enter a higher amount and try again. * 122 - The Payment Date is invalid. Please enter a different date. * 128 - The Settlement Date is invalid. Please enter a different date. * 130 - The length of the supplied BPAY Customer Reference Number is not valid for this Biller. Please check your entry and try again. * 131 - The amount you have entered is not correct or not accepted by the Biller. Please check your entry and try again. * 132 - Only numeric values are allowed for BPAY Customer Reference Number.  Please remove any special characters such as '-' or '_' or spaces and try again. * 133 - The Payment Date you have entered is not correct or has past the date accepted by the Biller. Please check your entry and try again. * 140 - The amount entered is more than the maximum amount accepted by the Biller. Please enter a lower amount and try again.
    */
    'validationErrorDescription'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "validationResponseCode",
            "baseName": "validationResponseCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "validationErrorDescription",
            "baseName": "validationErrorDescription",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValidationSummary.attributeTypeMap;
    }
    
    public constructor() {
    }
}

